couchdb: &couchdb
  protocol: http
  host: localhost
  port: 5984
  design: dolly
  username: 
  password: 
  name: test

travis: &travis
  default:
    <<: *couchdb
    username:
    password:

development:
  default:
    <<: *couchdb
  partitioned:
    <<: *couchdb
    name: partitioned
  design_skipped:
    <<: *couchdb
    name: design_skipped
    skip_migrations: true

test:
  default:
    <<: <%= ENV['TRAVIS'] ? "*travis" : "*couchdb" %>
  partitioned:
    <<: <%= ENV['TRAVIS'] ? "*travis" : "*couchdb" %>
    name: partitioned

staging:
  default:
    <<: *couchdb

production:
  default:
    <<: *couchdb
